name: L5Kit-Wheel

on:
  push:
    tags: [ '*' ]

jobs:
  build-deploy-wheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up Poetry
      uses: Gr1N/setup-poetry@v2
      with:
        poetry-version: 1.0.10
    - name: Build Wheel
      working-directory: l5kit
      run: |
        poetry run pip install --upgrade pip
        poetry build
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')  # publish only on annotate commits
      uses: pypa/gh-action-pypi-publish@v1.2.2
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        packages_dir: l5kit/dist/
